name: Pull Request Tests
run-name: PR check
on:
  pull_request_target:

jobs:
  run-tests:
    runs-on: ubuntu-24.04
    permissions:
      pull-requests: write
    environment: testing
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          submodules: 'false'

      - name: Fetch PR’s HEAD for testing
        run: git fetch origin +refs/pull/${{ github.event.pull_request.number }}/merge

      - name: 'Show ENV'
        run: env
